<script type="text/javascript" src="/js/MooTools-Core-1.6.0-compressed.js"></script>

<link rel="stylesheet" href="/portal/ontraport/css/header.css">
<link rel="stylesheet" href="/portal/ontraport/css/tp.css">

<div class="contentBox pcb-box10">
    <div>
      <div>
        <div>
          <form id="form1" autocomplete="Off">
            <h4>
              &#191;Estás interesado en invertir?
              <br>
              <span>Contáctanos y recibe la mejor asesoría.</span>
            </h4>
            <div>
              <input type="text" title="Nombre(s)" id="nombre" name="nombre" placeholder="Nombre (s)" maxlength="40">
              <input type="text" title="Apellido Paterno" id="apellidopaterno" name="apellidopaterno" placeholder="Apellido Paterno" maxlength="80">
              <input type="text" title="Apellido Materno" id="apellidomaterno" name="apellidomaterno" placeholder="Apellido Materno" maxlength="80">
              <input type="text" title="Email" id="email" name="email" placeholder="Email" maxlength="80">
              <input type="tel" title="Teléfono" id="celular" name="celular" placeholder="Teléfono (10 dígitos) " maxlength="10">
              <span>
                <input type="checkbox" id="agree">
                Acepto Términos y Condiciones
              </span>
            </div>
            <p id="errorMsg2"></p>
            <button id="submit1" type="button" class="buttonP">solicita tu coaching financiero</button>
          </form>
        </div>
      </div>
    </div>
  </div>

<script src="/portal/ontraport/js/tp.js"></script>