<style>
<!--
body{
background-color:rgb(234, 234, 238);
}
-->
</style>

<div class="col-100 fleft">
<div class="main970 margin-LRauto">
<div class="main970 fleft margin-T10">
	<h1>La p&aacute;gina que solicitaste se encuentra en mantenmiento temporal</h1>
	<img width="600px" src="/assets/img/fazteca.png" />
</div>
<?php if ('production' != $this->env || $_GET['debug'] == 'view'): ?>
<h1>Ha ocurrido un error</h1>
<h3>Informaci&oacute;n de excepci&oacute;n:</h3>
<p>
	<b>Mensaje:</b>
	<?php echo $this->exception->getMessage() ?>
</p>

<h3>Traza:</h3>
<pre>
	<?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Par&aacute;metros:</h3>
<pre>
	<?php var_dump($this->request->getParams()) ?>
</pre>
<?php endif ?>

</div>
</div>
</div>