<footer class="w3-col s12 m12 l12">
        <div class="w3-col s12 m12 l12 tell">
	 <div class="w3-col s12 m12 l12 wrapper">
            <div class="w3-col s12 m12 l3 imaLft">
                <img src="/assets/v2/images/dime.png" alt="Fundación Azteca">
            </div>
            <div class="w3-col s12 m12 l9 texto">
                <p>A trav&eacute;s de Dime... Fundaci&oacute;n Azteca comp&aacute;rtenos tus dudas, sugerencias, 
                    reconocimientos o cualquier inquietud que nos ayude a seguir generando 
                    acciones positivas para transformar nuestro pa&iacute;s. 
                    <a href="https://dimefundacionazteca.dialogus.com.mx/hc/es" target="_blank">
                        <b>Cont&aacute;ctanos aquí</b>
                    </a>
                </p>
            </div>
	 </div>
        </div>
        <div class="w3-col s12 m12 l12 blackened">
            <div class="w3-col s12 m6 l4 data">
                <div class="w3-col s12 m12 l12 socials">
                    <ul>
                        <li><a href="https://twitter.com/FundacionAzteca" target="_blank"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="https://www.instagram.com/fundacionazteca/" target="_blank"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="https://www.facebook.com/FundacionAzteca" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="https://www.youtube.com/user/FundacionAztecaOf" target="_blank"><i class="fab fa-youtube"></i></a></li>
                    </ul>
                </div>
                <div class="w3-col s12 m12 l12 logoFtr">
                    <img src="/assets/v2/images/logo-fazteca.png" alt="Fundación Azteca">
                </div>
                <div class="w3-col s12 m12 l12 adress">
                    <pº>Todos los derechos reservados</p>
                    <p>&copy;Fundación Azteca 2020</p>
                    <p class="montes">Montes Urales 460, Lomas de Chapultepec III Sección C.P. 11000, CDMX, Piso 2.</p>
                </div>
            </div>
        </div>
</footer>
