<!-- NAVIGATION -->
    <header class="w3-col s12 m12 l12">
       <div class="col s12 m12 l12">
	        <ul class="head wrapper">
	          <li class="logo">
	            <a href="/contenido/seccion/home">
	              <img src="/assets/v2/images/logo_fundacion.png" alt="Fundación Azteca">
	            </a>
	          </li>
	          <li id="socialBar">  
		          <ul class="socialBar">
		            <!-- <li class="donar">
		              <a href="#">Donar</a>
		            </li> -->
		            <li><a href="https://twitter.com/FundacionAzteca" target="_blank"><img src="/assets/v2/images/twitter.svg" alt=""></a></li>
					<li><a href="https://www.facebook.com/FundacionAzteca/" target="_blank"><img src="/assets/v2/images/facebook.svg" alt=""></a></li>
		            <li><a href="https://www.instagram.com/fundacionazteca" target="_blank"><img src="/assets/v2/images/instagram.svg" alt=""></a></li>
		            <li><a href="https://www.youtube.com/channel/UC3zSmRGuJk1_joOp1FSXLUw" target="_blank"><img src="/assets/v2/images/youtube.svg" alt=""></a></li>
		          </ul>
	          </li>
	        </ul>
	      <nav class="w3-col s12 m12 l12 barsMenu">
	        <a href="#" id="openMenu"><i class="fal fa-bars"></i></a>
	        <ul class="col s10 menuTab" id="menuTab">
	                <li id="closeMenu"><img src="/assets/v2/images/logo_fundacion.png" alt="Fundación Azteca"><i class="fal fa-times"></i></li>
	                <li><a href="/contenido/seccion/home">Inicio</a></li>
					<li class="nosotros"><a href="#">Nosotros</a>
						<ul class="subMenu">
							<li class="noticias"><a href="/contenido/seccion/nosotros">Nosotros</a></li>
							<li><a href="/assets/politica_antisoborno.pdf">Política Antisoborno</a></li>
							<li><a href="/assets/codigo_de_etica_y_de_conducta.pdf">Código de Ética y de Conducta</a></li>
						</ul>
					</li>
	                <li><a href="/contenido/seccion/comunidad">Comunidad</a></li>
	                <li><a href="/contenido/seccion/programaseducativos">Programas Educativos</a></li>
	                <li><a href="/contenido/seccion/programasambientales">Programas Ambientales</a></li>
	                <li><a href="/contenido/noticias/historico">Noticias</a></li>
	                <li><a href="/contenido/seccion/contacto">Contacto</a></li>
	                <li><a href="https://dimefundacionazteca.dialogus.com.mx/hc/es" target="_blank">Dime <br><span>(Contacto, dudas y comentarios)</span></a></li>
					<li class="donativo">
						<a href="https://fundacionazteca.secure.force.com/donar/" >Dona aquí</a>
					</li>
	        </ul>
	      </nav>
      </div>
    </header>
<!-- NAVIGATION END -->
