<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Fundaci&oacuten Azteca</title>
    
    <link rel="icon" type="image/png" href="/assets/v2/images/favicon-32x24.png">
    <link rel="icon" type="image/png" href="/assets/v2/images/favicon-16x12.png">

    <link rel="stylesheet" href="/assets/v2/styles/index.css">
    <link rel="stylesheet" href="/assets/v2/styles/base.css">

</head>
<body>

<div class="w3-col s12 m12 l12 backBack">

    <div class="w3-col s12 m12 l12 imaLogo">
        <img src="/assets/v2/images/fundacionaztecaw.png" alt="Fundacion Azteca">
    </div>

    <div class="item item--css-background-clip">
        <div class="demo">
            <span>bieNveNido</span><br>
            CoNtigo por México
        </div>
    </div>

    <div class="w3-col s12 m12 l4 texto">
        <p>Somos el principal brazo social de Grupo Salinas, que por más de 20 años ha creado valor social, ambiental y educativo, a través de programas de alto impacto y sinergias con el sector público y la ciudadanía.</p>
    </div>
    <div class="w3-col s12 m12 l12 anchor">
        <a href="/contenido/seccion/home">Entrar</a>
    </div>
</div>

</body>
</html>