<?php
	$this->headLink()->appendStylesheet('/assets/v2/styles/animate.css');
	$this->headLink()->appendStylesheet('/assets/v2/styles/interna.css');
?>
    <div class="w3-col s12 m12 l12">     
        <section class="w3-col s12 m12 l12 fixedBG ">
            <div class="w3-col s12 m12 l12 community">
                <div class="w3-col s12 m8 l8">
                    <h2>Comunidad</h2>
                    <p>Promovemos pr&aacute;cticas socialmente responsables</p>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>Mantener una estrecha relaci&oacute;n con nuestros grupos de inter&eacute;s es vital para promover pr&aacute;cticas socialmente responsables, que permiten la construcci&oacute;n de mejores comunidades mediante un modelo de sostenibilidad que desarrolle soluciones econ&oacute;micas-resilientes.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft commu animated">
                    <img src="/assets/v2/images/foto-movimiento.png" alt="Fundaci&oacuten Azteca">
                    <img src="/assets/v2/images/logo-movimiento.png" alt="Fundaci&oacuten Azteca">
                    <p>Es la campa&ntilde;a de corresponsabilidad social a trav&eacute;s de la cual Fundaci&oacute;n Azteca apoya a organizaciones y proyectos de la sociedad civil, con el ﬁn de alcanzar un mayor n&uacute;mero de audiencia para generar conciencia y atraer recursos. La sociedad es invitada, a trav&eacute;s de una campa&ntilde;a medi&aacute;tica intensiva, a realizar sus aportaciones, apoyando a organizaciones serias que deseen crear soluciones y conciencia sobre problemas espec&iacute;ﬁcos que transformen M&eacute;xico.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay comm">
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>Las Organizaciones de la Sociedad Civil – que contribuyen a enfrentar desaf&iacuteos en materia de salud, educaci&oacuten, prevenci&oacuten, bienestar y ambiental que el sector p&uacuteblico no puede atacar – enfrentan diﬁcultades para la obtenci&oacuten de recursos para concretar sus proyectos.</p>
                    <h4>¿C&oacutemo lo hace?</h4>
                    <p>A trav&eacute;s de campa&ntilde;as medi&aacuteticas de responsabilidad social que generan conciencia y vinculaci&oacute;n sobre temas sociales relevantes y abren espacios para que las Organizaciones de la Sociedad Civil obtengan recursos.</p>
                    <h4>¿Qu&eacute resultados busca en el corto plazo?</h4>
                    <p>Apoyar la labor de Organizaciones de la Sociedad Civil con el objetivo de generar valor social y nuevas oportunidades de desarrollo.</p>
                    <p>Tras los sismos del 7 y 19 de septiembre de 2017, en el marco del Movimiento Azteca No. 100, se recaudaron fondos para implementar un programa de autoconstrucci&oacute;n de vivienda que atendiera a los daminiﬁcados.</p>
                    <p>Se logr&oacute; recaudar m&aacute;s de $92 millones de pesos. Esos recursos permitieron que durante 2018 se entregaran 525 casas para reconstruir sus hogares en cinco estados de la Rep&uacuteblica Mexicana:</p>
                    <ul>
                        <li>20 en Puebla</li>
                        <li>72 en Morelos</li>
                        <li>121 en Chiapas</li>
                        <li>132 en el Estado de M&eacute;xico</li>
                        <li>180 en Oaxaca</li>
                    </ul>
                    <div class="w3-col s12 m12 l12 link">
                        <p><span>Visitar sitio:</span></p>
                        <a href="https://movimientoazteca.org/" target="_blank">movimientoazteca.org</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>Gestión responsable de los recursos naturales y empoderamiento de las comunidades a las que pertenecemos.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft scndrw animated">
                    <img src="/assets/v2/images/foto-redsocial.png" alt="Fundaci&oacuten Azteca">
                    <img src="/assets/v2/images/logo-redsocial.png" alt="Fundaci&oacuten Azteca">
                    <p>Es una red de organizaciones de la sociedad civil a lo largo de todo el país que busca el desarrollo de capacidades, alianzas y sinergias, para generar valor social que se materialice en prosperidad incluyente.</p>
                    <p>Donativo Hormiga Acción dirigida a apoyar a pequeñas y medianas organizaciones civiles que enfocan sus esfuerzos en sectores vulnerables, mediante donativos en especie de electrodomésticos y equipamiento. Grupo Elektra y Banco Azteca se suman como pilar de este proyecto.</p>
                    <p>Encuentro de Organizaciones Civiles En Red Social Azteca hemos apostado por el desarrollo de capacidades de los ciudadanos, en beneﬁcio de México. Por ello, en 2018 convocamos por tercer año consecutivo a un encuentro con organizaciones que atienden y apoyan una gran diversidad de causas de relevancia social.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay comm">
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>La falta de capacidades y empoderamiento de las Organizaciones de la Sociedas Civil para desarrollar soluciones eﬁcaces a los problemas que afectan a sus comunidades.</p>
                    <h4>¿C&oacutemo lo hace?</h4>
                    <p>Creando capacidades para que a través del emprendimiento social mejoren las condiciones de vida de su comunidad.</p>
                    <h4>¿Qu&eacute resultados busca en el corto plazo?</h4>
                    <p>Empoderar a las Organizaciones de la Sociedad Civil que buscan transformar su entorno y generar un impacto positivo en su comunidad.</p>
                    <div class="w3-col s12 m12 l12 link">
                        <p><span>Visitar sitio:</span></p>
                        <a href="https://www.tvazteca.com/fundacion/redsocial/" target="_blank">redsocialazteca.mx</a>
                    </div>
                </div>
            </div>
        </section>
    </div>
<script type="text/javascript" src="/assets/js/MooTools-Core-1.6.0-compressed.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/headfoot.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/interna.js"></script>