<?php
	$this->headLink()->appendStylesheet('/assets/v2/styles/animate.css');
	$this->headLink()->appendStylesheet('/assets/v2/styles/interna.css?v=1');
?>
    <div class="w3-col s12 m12 l12 content">

        <section class="w3-col s12 m12 l12 directorio">
            
            <h2>Contacto <br><i class="fal fa-minus"></i></h2>

            <div class="w3-col s12 m12 l12 dirItem">
                <p>En Fundación Azteca de Grupo Salinas estamos contigo, si deseas contactarnos escríbenos un mail a: <a href="mailto:dime@fundacionazteca.com.mx">dime@fundacionazteca.com.mx</a></p>
            </div>

        </section>        
    </div>
<script type="text/javascript" src="/assets/js/MooTools-Core-1.6.0-compressed.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/headfoot.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/interna.js"></script>
