  <!-- DIME -->
<div class="caja1a">
	<img src="/assets/img/dime.png">
</div>

<div class="caja2">
	<p>A través de Dime... Fundación Azteca compártenos tus dudas, sugerencias, reconocimientos o cualquier inquietud que nos ayude a seguir generando acciones positivas para transformar nuestro país.<a href="https://dimefundacionazteca.dialogus.com.mx/hc/es" target="_blank" style="color:#666; font-weight: bold; padding-left: 10px; text-decoration: underline;">Contáctanos aquí</a></p>
</div>
  <!-- END DIME -->