<?php
	$this->headLink()->appendStylesheet('/assets/v2/styles/animate.css');
	$this->headLink()->appendStylesheet('/assets/v2/styles/interna.css');
?>
    <div class="w3-col s12 m12 l12 content">

        <section class="w3-col s12 m12 l12 directorio">
            
            <h2>Directorio <br><i class="fal fa-minus"></i></h2>

            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Director General</span></p>
                <p>Antonio Domínguez Sagols <span class="slash">&#8725; </span><a href="mailto:adominguezs@gruposalinas.com.mx">adominguezs@gruposalinas.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Administración y Finanzas</span></p>
                <p>Alfonso Manuel Reza Franco <span class="slash">&#8725; </span><a href="mailto:areza@tvazteca.com.mx">areza@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Orquestas Sinfónicas y Coros Esperanza Azteca</span></p>
                <p>Ricardo Obert Martínez <span class="slash">&#8725; </span><a href="mailto:omartinezr@tvazteca.com.mx">omartinezr@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Proyectos Educativos</span></p>
                <p>Coral Berenice Pérez Amaya <span class="slash">&#8725; </span><a href="mailto:coral.perez@tvazteca.com.mx">coral.perez@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">¡Qué Viva la Selva Lacandona!</span></p>
                <p>Krystell Padilla Sayago <span class="slash">&#8725; </span><a href="mailto:krystell.padilla@tvazteca.com.mx">krystell.padilla@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Limpiemos México</span></p>
                <p>Alma Lucía Arzaluz Alonso <span class="slash">&#8725; </span><a href="mailto:aarzaluza@gruposalinas.com.mx">aarzaluza@gruposalinas.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Enlace con Organizaciones de la Sociedad Civil</span></p>
                <p>César Rivas Valdivia <span class="slash">&#8725; </span><a href="mailto:cesar.rivas@gruposalinas.com.mx">cesar.rivas@gruposalinas.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Movimiento Azteca</span></p>
                <p>Martha Lidia López Ortiz <span class="slash">&#8725; </span><a href="mailto:martha.lopez@tvazteca.com.mx">martha.lopez@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Vive Sin Drogas</span></p>
                <p>Juan Carlos Benasco Rodríguez <span class="slash">&#8725; </span><a href="mailto:jbenasco@tvazteca.com.mx">jbenasco@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Evaluación y Transparencia</span></p>
                <p>Marcela Rubio Sánchez <span class="slash">&#8725; </span><a href="mailto:marcela.rubio@tvazteca.com.mx">marcela.rubio@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Procuración de Fondos</span></p>
                <p><a href="mailto:donantes@tvazteca.com.mx">donantes@tvazteca.com.mx</a></p>
            </div>
            <div class="w3-col s12 m12 l12 dirItem">
                <p><span class="cgo">Jurídico</span></p>
                <p>Josefina Hernández Hernández <span class="slash">&#8725; </span><a href="mailto:josefina.hernandez@tvazteca.com.mx">josefina.hernandez@tvazteca.com.mx</a></p>
            </div>

        </section>        
    </div>
<script type="text/javascript" src="/assets/js/MooTools-Core-1.6.0-compressed.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/headfoot.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/interna.js"></script>