<?php
	$this->headLink()->appendStylesheet('/assets/v2/styles/interna.css');
?>
<style>
/* Media Query for Mobile Devices */ 
@media only screen and (max-width: 765px) { 
.margenImagen {margin-top: 10px}
.memIma img { width: 130%;margin-left:-20px} 
} 
/* Media Query for Desktop Devices */ 
@media only screen and (min-width:768px) {
.margenImagen {margin-top: 100px}
.memIma img { width: 100%;} 
}
/* Media Query for Desktop Devices */ 
@media only screen and (min-width:1024px) {
.margenImagen {margin-top: 200px}
.memIma img { width: 100%;} 
}
</style>
        <section class="w3-col s12 m12 l12 content firstRow">
        	<div class="w3-col s12 m12 l12 memIma">
				<a href="https://fundacionazteca.org/archivos/memoriaFundacionAzteca.pdf" target="_blank" rel="noopener">
					<img src="/assets/v2/images/memoriaFundacionAzteca.png" alt="Fundación Azteca">
				</a>
			</div>
            <div class="w3-col s12 m12 l12">
                <div class="w3-col s12 m3 l3 imgn">
                    <img src="/assets/v2/images/gsalinas.png" alt="Fundación Azteca">
                </div>
                <div class="w3-col s12 m9 l9">
                    <p>Grupo Salinas es un conjunto de empresas din&aacute;micas de r&aacute;pido crecimiento y a la vanguardia tecnol&oacute;gica con enfoque en la creaci&oacute;n de valor econ&oacute;mico, social y ambiental.</p>
                </div>
            </div>
            <div class="w3-col s12 m12 l12">
                <div class="w3-col s12 m3 l3 imgn">
                    <img src="/assets/v2/images/fazteca.png" alt="Fundación Azteca">
                </div>
                <div class="w3-col s12 m9 l9">
                    <p>Fundaci&oacute;n Azteca es el principal brazo social de Grupo Salinas, que por m&aacute;s de 20 a&ntilde;os ha creado valor social, ambiental, educativo y cultural a trav&eacute;s de programas de alto impacto, sinergias con el sector p&uacute;blico y los ciudadanos de M&eacute;xico.</p>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 content msnvsn">
            <div class="w3-col s12 m12 l12">
                <div class="w3-col s12 m6 l6 pad16">
                    <h2>Misi&oacute;n</h2>
                    <p>Crear y potenciar capacidades en la sociedad para mejorar su calidad de vida a trav&eacute;s de una educaci&oacute;n basada en libertad, imaginaci&oacute;n, creatividad, innovaci&oacute;n y colaboraci&oacute;n.</p>
                </div>
                <div class="w3-col s12 m6 l6 pad16">
                    <h2>Visi&oacute;n</h2>
                    <p>Ser reconocida como la organizaci&oacute;n m&aacute;s relevante de M&eacute;xico en impulsar una educaci&oacute;n transformadora, que genera prosperidad, por medio de la identificaci&oacute;n del talento y basada en fomentar la libertad, imaginaci&oacute;n, creatividad, innovaci&oacute;n y colaboraci&oacute;n para formar agentes de cambio social; promoviendo valores y generando identidad, compromiso y orgullo de pertenencia en sus participantes y aliados.</p>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 content aidien">
            <img src="/assets/v2/images/adn.jpg" alt="Fundación Azteca">
        </section>

        <section class="w3-col s12 m12 l12 dudesBg">
            <div class="w3-col s12 m12 l12 content">
                <div class="w3-col s12 m4 l4">
                    <h2>Mejoramiento de la calidad de vida de las comunidades en educaci&oacute;n, cultura y salud</h2>
                    <p>Orquestas sinf&oacute;nicas y coros
                        Esperanza Azteca
                        Plantel Azteca
                        Rob&oacute;tica
                        Programa de Becas
                        Modelo de Aprendizaje colaborativo
                        Vive sin Drogas</p>
                </div>
                <div class="w3-col s12 m4 l4">
                    <h2>Educaci&oacute;n Ambiental</h2>
                    <p>¡Qué viva la Selva Lacandona!
                        Limpiemos M&eacute;xico</p>
                </div>
                <div class="w3-col s12 m4 l4">
                    <h2>Vinculaci&oacute;n y fortalecimiento de la vida comunitaria</h2>
                    <p>Red Social Azteca
                        Movimiento Azteca
                        Autoconstrucci&oacute;n de vivienda</p>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12">
            <div class="w3-col s12 m12 l12 content statsRow">
                <div class="w3-col s12 m6 l6">
                    <h2>VINCULACI&Oacute;N CON LOS OBJETIVOS DE DESARROLLO SOSTENIBLE</h2>
                    <p>En septiembre de 2015, 193 Estados adoptaron la Agenda 2030,en la cual se establecieron 17 Objetivos de Desarrollo Sostenible que buscan erradicar la pobreza, proteger el planeta y asegurar la prosperidad para todos.</p>
                    <p>El ADN de Grupo Salinas y la misi&oacute;n de Fundaci&oacute;n Azteca est&aacute;n en l&iacute;nea con la Agenda 2030, por lo que nuestros programas est&aacute;n contribuyendo con los Objetivos de Desarrollo Sostenible.</p>
                </div>
                <div class="w3-col s12 m6 l6">
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/1-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/2-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/3-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/4-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/5-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/6-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/7-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/8-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/9-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/10-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/11-200x200.png" alt="Fundación Azteca"></div>
                    <div class="w3-col s3 m3 l3 statItm"><img src="/assets/v2/images/12-200x200.png" alt="Fundación Azteca"></div>
                </div>
            </div>
        </section>        
    </div>
<script type="text/javascript" src="/assets/js/MooTools-Core-1.6.0-compressed.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/headfoot.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/interna.js"></script>