<?php
	$this->headLink()->appendStylesheet('/assets/v2/styles/animate.css');
	$this->headLink()->appendStylesheet('/assets/v2/styles/interna.css');
?>
    <div class="w3-col s12 m12 l12">
     
        <section class="w3-col s12 m12 l12 fixedBG">
            <div class="w3-col s12 m12 l12 environmental">
                <div class="w3-col s12 m8 l8">
                    <h2>Programas Ambientales</h2>
                    <p>El medio ambiente toma lugar prioritario en nuestra comunidad.</p>
                </div>
            </div>
        </section>
        
        <section class="w3-col s12 m12 l12 conLogo">
            <p>El medio ambiente toma lugar prioritario en nuestra comunidad, por ello creamos valor ambiental al atenuar los impactos negativos e innovamos en programas ambientales con resultados positivos en la mitigación de la huella de carbono, reducción de consumo de energía y uso responsable del agua.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft enviro animated">
                    <img src="/assets/v2/images/foto-canoas.png" alt="Fundaci&oacuten Azteca">
                    <img src="/assets/v2/images/logo-selva.png" alt="Fundaci&oacuten Azteca">
                    <p>Es un programa que promueve la conservación ambiental a través de un concurso que convoca a los niños y jóvenes de 9 a 15 años de edad. Quienes mandan un dibujo y texto alusivos a la conservación de la Selva Lacandona. Un jurado elige 37 dibujos ganadores, uno por cada Estado de la República, 3 de hijos de colaboradores de Grupo Salinas y 2 de Planteles Azteca. Los ganadores viajan 6 días a la Estación Chajul, ubicada en el corazón de la Selva Lacandona, en el Estado de Chiapas, en compañía de guías, niños lacandones y biólogos.</p>
                    <p>Con el propósito de evitar la deforestación y conservar las hectáreas de selva sana que aún existen, el programa también apoya con la promoción de los proyectos productivos sustentables que se encuentran funcionando dentro de la Selva Lacandona: Hotel Canto de la Selva, Campamento Tamandúa, Selvaje, La Casa del Morpho y el Restaurante Bellavista.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay envi">
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>La desinformación entre los niños y jóvenes sobre la importancia de la Selva Lacandona y su biodiversidad.</p>
                    <h4>¿C&oacute;mo lo hace?</h4>
                    <p>A través de un viaje educativo a la Selva Lacandona, se enseña a los jóvenes ganadores del concurso sobre la importancia de la conservación de nuestras áreas naturales protegidas y la biodiversidad. Además se brinda apoyo directo con capacitaciones a los proyectos sustentables para su desarrollo.</p>
                    <h4>¿Qué resultados busca en el corto plazo?</h4>
                    <p>Concientizar a jóvenes sobre la importancia de la conservación de la selva y que ellos a su vez concienticen a su entorno. Mejorar el servicio que se ofrece en los proyectos para atraer un mayor número de ecoturistas y mantener en funcionamiento las empresas para garantizar la conservación de la selva.</p>
                    <div class="w3-col s12 m12 l12 link">
                        <p><span>Visitar sitio:</span></p>
                        <a href="http://quevivalaselvalacandona.org/" target="_blank">quevivalaselvalacandona.org</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>Promovemos el cambio hacia una cultura de responsabilidad ambiental que beneﬁcie a nuestras familias y entorno.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft enviro animated">
                    <img src="/assets/v2/images/foto-limpiemos.png" alt="Fundaci&oacuten Azteca">
                    <img src="/assets/v2/images/logo-limpiemos.png" alt="Fundaci&oacuten Azteca">
                    <p>Es una campaña permanente de acción, educación y conciencia ambiental, con especial énfasis en niños y jóvenes. Se busca poner en acción a la comunidad sobre el problema de la basura y sus soluciones, invitando a un movimiento de limpieza.</p>
                    <p>Se unen al esfuerzo instituciones, gobiernos y voluntarios de la sociedad civil. También impulsamos acciones permanentes a través de programas en los estados, ciudades y municipios Orgullosamente Limpios donde ya han participado: Cd. del Carmen, Torreón y Desierto de los Leones.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay envi">
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>La contaminación por desechos sólidos.</p>
                    <h4>¿C&oacute;mo lo hace?</h4>
                    <p>A través de campañas de limpieza, reclutando brigadas de voluntarios para limpiar alguna zona que los voluntarios identiﬁcan. Existe una campaña permanente, Desierto de los Leones Limpio, en la cual se organizan jornadas a lo largo de todo el año, se dan cursos de capacitación y jornadas de educación.</p>
                    <p><b>Además, en 2018</b> se realizaron dos concursos:</p>
                    
                    <ul>
                        <li><b>Líderes ambientales:</b> los líderes de brigada con mejor desempeño en el año son premiados.</li>
                        <li><b>Recicla:</b> a través de una convocatoria a universidades y sociedad civil en general, se presentan proyectos innovadores de reciclaje.</li>
                    </ul>

                    <div class="w3-col s12 m12 l12 link">
                        <p><span>Visitar sitio:</span></p>
                        <a href="https://limpiemosmexico.mx/" target="_blank">limpiemosmexico.mx</a>
                    </div>
                </div>
            </div>
        </section>
    </div>
<script type="text/javascript" src="/assets/js/MooTools-Core-1.6.0-compressed.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/headfoot.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/interna.js"></script>