<?php
	$this->headLink()->appendStylesheet('/assets/v2/styles/animate.css');
	$this->headLink()->appendStylesheet('/assets/v2/styles/interna.css');
?>
    <div class="w3-col s12 m12 l12">
     
        <section class="w3-col s12 m12 l12 fixedBG">
            <div class="w3-col s12 m12 l12 educational">
                <div class="w3-col s12 m8 l8">
                    <h2>Programas Educativos y Culturales</h2>
                    <!-- <p>La educación es la base para mejorar <br> nuestra vida.</p> -->
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>La educación es la base para mejorar nuestra vida y el desarrollo sostenible.
                Además de mejorar la calidad de vida de las personas, el acceso a educación
                de calidad y excelencia que impulsa la meritocracia.</p>
        </section>
        
        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft educa animated">
                    <img src="/assets/v2/images/foto-plantel.png" alt="Fundaci&oacuten Azteca">
                    <img src="/assets/v2/images/logo-plantel.png" alt="Fundaci&oacuten Azteca">
                    <p>Plantel Azteca Ciudad de México es la primera institución educativa privada a nivel secundaria y bachillerato tecnológico donde jóvenes con alto rendimiento escolar, en situación social desfavorable, obtienen una educación gratuita de calidad, excelencia y que promueve la meritocracia. Se implementa el Modelo de Intervención Educativa Azteca, que tiene como eje rector la autonomía en los procesos de aprendizaje, mediante la incorporación de metodologías activas y ambientes digitales. Asimismo, la ﬁlosofía del modelo promueve los valores y una formación integral, además de que se enfoca en desarrollar las competencias de los estudiantes a través de clases extracurriculares en temas de vanguardia como la robótica e inglés avanzado.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay educ">
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>La falta de oportunidades para los alumnos destacados.</p>
                    <h4>¿Qu&eacute resultados busca en el corto plazo?</h4>
                    <p>Promedio global por generación igual o mayor a 8.5</p>
                    <p><img src="/assets/v2/images/alumnos1.png" alt="Fundación Azteca"></p>
                    <p><b>9 de cada 10</b> alumnos continuarán sus estudios de bachillerato y universidad</p>
                    <p><img src="/assets/v2/images/alumnos2.png" alt="Fundación Azteca"></p>
                    <p><b>9 de cada 10</b> alumnos certiﬁcados en el nivel B1 (secundaria) y B2 (bachillerato) de inglés con base al Marco Común Europeo de Referencia para Lenguas (MCERL)</p>

                    <div class="w3-col s12 m12 l12">
                        <div class="w3-col s12 m12 l3 center">
                            <img class="maxW30" src="/assets/v2/images/alumnos3.png" alt="Fundación Azteca">
                        </div>
                        <div class="w3-col s12 m12 l9">
                            <h3 class="gigantic">100%</h3>
                            <p>de los docentes de inglés certiﬁcados en el nivel C1 con base al MCERL</p>
                        </div>
                    </div>
                    <div class="w3-col s12 m12 l12">
                        <div class="w3-col s12 m12 l3 center">
                            <img class="maxW30" src="/assets/v2/images/alumnos3.png" alt="Fundación Azteca">
                        </div>
                        <div class="w3-col s12 m12 l9">
                            <h3 class="gigantic">100%</h3>
                        </div>
                        <div class="w3-col s12 m12 l12">
                            <p class="red">de los estudiantes formados con el Modelo Integral de Habilidades para la Vida, impulsado por la Organización Mundial de la Salud: empatía, comunicación asertiva, relaciones interpersonales, pensamiento creativo, pensamiento crítico, manejo de problemas y conﬂictos, toma de decisiones, autoconocimiento, manejo de emociones y sentimientos y manejo del estrés.</p>
                        </div>
                    </div>
                    <div class="w3-col s12 m12 l12 link">
                        <p><span>Visitar sitio:</span></p>
                        <a href="https://www.plantelazteca.mx/" target="_blank">plantelazteca.mx</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>Ayudando a abastecer a la población más vulnerable con las herramientas
                necesarias para desarrollar soluciones innovadoras a las problemas más
                grandes del mundo.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft educa animated">
                    <img src="/assets/v2/images/new_row_1.png" alt="Fundaci&oacuten Azteca">
                    <!-- <img src="/assets/v2/images/logo-plantel.png" alt="Fundaci&oacuten Azteca"> -->
                    <p class="giganticP">Modelo Educativo para <br> Talento y Liderazgo.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay educ">
                    <ul class="redDisc">
                        <li><p>Intervenir en los procesos de enseñanza-aprendizaje de los planteles públicos del país través de la implementación de un <span class="enred">Modelo de Intervención Educativa innovador e integral.</span></p></li>
                        <li><p>Incidir en el <span class="enred">desarrollo científico, económico, político, social y cultural</span> del país a través de una educación de calidad.</p></li>
                        <li><p>Identiﬁcar y potencializar el <span class="enred">talento</span> de los niños y jóvenes mexicanos con la ﬁnalidad de contar con egresados altamente competentes y con una sólida formación integral.</p></li>
                        <li><p>Al tener recursos limitados, nos enfocamos en <span class="enred">potencializar las habilidades de los niños mas talentosos</span>, con el ﬁn de que se formen <span class="enred">futuros agentes de cambio.</span></p></li>
                    </ul>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>Potenciamos el talento de los estudiantes mexicanos de planteles públicos a través de una educación de calidad basada en valores.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft educa animated">
                    <img src="/assets/v2/images/new_row_2.png" alt="Fundaci&oacuten Azteca">
                    <img src="/assets/v2/images/logo-esperanza.png" alt="Fundaci&oacuten Azteca">
                    <p>Esperanza Azteca es un programa social enfocado en la formación musical mediante la creación de orquestas sinfónicas y coros para jóvenes de 7 a 25 años de escasos recursos, cuya misión es formar mejores seres humanos a través de la enseñanza de la música.</p>
                    <p>Los objetivos de las Orquestas Sinfónicas y Coros Esperanza Azteca son:</p>
                    <ul>
                        <li>Contribuir al desarrollo humano integral de niños y jóvenes.</li>
                        <li>Fortalecer su autoestima y sentido de pertenencia.</li>
                        <li>Alejarlos de factores de riesgo</li>
                        <li>Contribuir a la creación y mantenimiento de tejido social sano.</li>
                        <li>Fortalecer la calidad de la educación musical en México.</li>
                    </ul>
                </div>
                <div class="w3-col s12 m6 l6 toStay educ">
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>La niñez y la juventud están expuestas a factores adversos como la pobreza, las adicciones, la delincuencia, la desintegración familiar y la ausencia de oportunidades.</p>
                    <h4>¿C&oacutemo lo hace?</h4>
                    <p>A través de la enseñanza musical de excelencia (clases de lunes a viernes, cuatro horas diarias), adquieren disciplina y se refuerza la responsabilidad, la autonomía, el respecto, la excelencia y el trabajo en equipo. Es una alternativa que permite el desarrollo de capacidades, competencias y habilidades creativas, productivas y de integración. Con esta metodología, en once meses, los jóvenes que no tienen ninguna formación musical son capaces de participar en un concierto de una orquesta sinfónica y coro, demostrándose a sí mismos y a su comunidad que todo es posible.</p>
                    <h4>¿Qu&eacute resultados busca en el corto plazo?</h4>
                    <p>Esperanza Azteca disminuye conductas de riesgo y genera en los estudiantes habilidades para la vida para forjar su liderazgo y fortalecer su autoestima, mejorando el desempeño académico y reduciendo la deserción escolar.</p>
                    
                    <div class="w3-col s12 m12 l12 link">
                        <p><span>Visitar sitio:</span></p>
                        <a href="https://fundacionazteca.org/contenido/noticias/articulo/3/convocatoria-de-audiciones-2021" target="_blank">esperanzaazteca.mx</a>
                    </div>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>Las orquestas y coros se preparan 11 meses para dar su Concierto Debut, que es su concierto de inauguración. Previamente, llevan a cabo 4 conciertos de fogueo, los cuales tienen como propósito prepararlos para el Debut.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft educa animated">
                    <img src="/assets/v2/images/foto-robotica.png" alt="Fundaci&oacuten Azteca">
                    <img class="hidden" src="/assets/v2/images/foto-robotica.png" alt="Fundaci&oacuten Azteca">
                    <h2>Rob&oacute;tica</h2>
                    <p>Dentro de los Planteles Azteca, se imparten clases extracurriculares de robótica. Consisten en actividades para desarrollar competencias en las ciencias exactas, trabajo en equipo y resolución de problemas, los cuales, se ponen en práctica a través de la participación en torneos nacionales e internacionales.</p>
                    <p>En alianza con FIRST (For Inspiration and Recognition of Science and Technology) Robotics – una organización no lucrativa cuyo objetivo es estimular a los jóvenes para que se involucren más en la ciencia y en la tecnología – Fundación Azteca patrocina concursos y campeonatos locales e internacionales de robótica.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay educ">
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>La ciencia y tecnología no está al alcance de los grupos vulnerables.</p>
                    <h4>¿C&oacutemo lo hace?</h4>
                    <p>Promueve la educación tecnológica a través de una enseñanza lúdica enfocada a desarrollar habilidades que les permiten competir a nivel mundial.</p>
                    <h4>¿Qu&eacute resultados busca en el corto plazo?</h4>
                    <p>Trabajo en equipo, destreza en el manejo de herramientas y maquinarias, diseño, construcción y programación, análisis y desarrollo de soluciones ante problemas reales, gusto por la ciencia y la tecnología, aplicación de las matemáticas y ciencias en el mundo real, pensamiento lógico y crítico, desarrollo de estrategias y alianzas con equipos de otras nacionalidades.</p>
                </div>
            </div>
        </section>

        <section class="w3-col s12 m12 l12 conLogo">
            <p>Uno de los puntos importantes es que los jóvenes, niñas y niños pueden inspirar a sus familias y comunidades a fortalecer el tejido social.</p>
        </section>

        <section class="w3-col s12 m12 l12 conFx">
            <div class="w3-col s12 m12 l12 flx">
                <div class="w3-col s12 m6 l6 toLft educa animated">
                    <img src="/assets/v2/images/foto-becas.png" alt="Fundaci&oacuten Azteca">
                    <img class="hidden" src="/assets/v2/images/foto-robotica.png" alt="Fundaci&oacuten Azteca">
                    <h2>Programa de Becas</h2>
                    <h3>México de 10</h3>
                    <h3>¿Cuál es el problema que busca resolver el programa?</h3>
                    <p>Deserción estudiantil por falta de recursos económicos.</p>
                    <h3>¿Cómo lo hace?</h3>
                    <p>Con becas de manutención a egresados con alto desempeño académico.</p>
                    <h3>¿Qué resultados busca en el corto plazo?</h3>
                    <p>Que los alumnos no abandonen sus estudios.</p>
                </div>
                <div class="w3-col s12 m6 l6 toStay educ">
                    <h2 class="becas">Becas <br> Generación <br> Bicentenario</h2>
                    <p>1,000 niñas y niños destacados fueron elegidos por la SEP, SNTE, Nacional Monte de Piedad y Fundación Azteca para recibir becas durante toda su preparación educativa hasta que terminen su licenciatura para apoyar sus estudios.</p>
                    <h4>¿Cu&aacute;l es el problema que busca resolver el programa?</h4>
                    <p>Abandono escolar por falta de recursos económicos.</p>
                    <h4>¿C&oacutemo lo hace?</h4>
                    <p>Con becas de manutención a alumnos con alto desempeño académico.</p>
                    <h4>¿Qu&eacute resultados busca en el corto plazo?</h4>
                    <p>Que los alumnos no abandonen sus estudios.</p>
                </div>
            </div>
        </section>
    </div>
<script type="text/javascript" src="/assets/js/MooTools-Core-1.6.0-compressed.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/headfoot.js"></script>
<script type="text/javascript" src="/assets/v2/scripts/interna.js"></script>
